### ISSUE TITLE
How to add Video Support?

### ISSUE THREAD

**Issue by anujdutt9** [Hyuto/yolov5-onnxruntime-web#2]
Hi, thanks for your work. Is there a way to add video inference support here? I am a bit new to the React world, so haven't been able to make it work fully. So, any guidance on adding that support will be really helpful.
Thanks.

**Comment by Hyuto** [comment]
Hello, well it's definitely possible to add video inference. You can start with creating video tag for the source and make `opencv.js` consume it to take every frame array and then do the inferencing like usual, but the performance is really awful. The reason for this is we can't switch `onnruntime-web` backend from `wasm` to `webgl` to improve performance, because there is operator in `YOLOv5` model that `onnxruntime-web` `webgl` backend doesn't support yet (I've tried it recently). The other reason is `YOLOv5` `onnx` model doesn't ship with `NMS` so we have to implement it manually and it definitely affect the performance. 

I think the best way to handle this by using `tensorflow.js` or doing inference in the backend (not in the browser) since the computation is more powerful in there. Because`YOLOv5` `tfjs` model is shipped with the original `NMS` and `tfjs-webgl` backend is definitely more mature than `onnxruntime-web`, I've already implement this you can check it at [Hyuto/yolov5-tfjs](https://github.com/Hyuto/yolov5-tfjs). If you choose to do inference in the backend you can check my other repo [Hyuto/yolov7-node](https://github.com/Hyuto/yolov7-node) and follow the steps on [#1](https://github.com/Hyuto/yolov7-node/issues/1) to serve `YOLOv5` model (I'm not using react on this repo so I think it's more easy to follow).

**Comment by Hyuto** [comment]
Just a little update here. I just update the model to be End2End model with NMS on it. Although the performance is increased it doesn't do much to speed up process to be able to do video inferencing. You can try it on the current master branch. 

I'm closing this issue here.
